name: Run on On-Prem Runner

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted  # Required for all self-hosted runners
    # Optional: Specify labels if you've set any (e.g., 'onprem')
    # runs-on: [self-hosted, onprem]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if Ansible is installed
        id: check_ansible
        run: |
          if ! command -v ansible &> /dev/null
          then
              echo "ansible_missing=true" >> "$GITHUB_OUTPUT"
          else
              echo "ansible_missing=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Install Ansible if missing
        if: steps.check_ansible.outputs.ansible_missing == 'true'
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Verify Ansible installation
        run: |
          ansible --version
          ls -la 
          #ansible-playbook site.yml -i localhost, -c local
