name: Run on On-Prem Runner

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted  # Required for all self-hosted runners
    # Optional: Specify labels if you've set any (e.g., 'onprem')
    # runs-on: [self-hosted, onprem]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo apt-add-repository --yes --update ppa:ansible/ansible
        sudo apt install -y ansible

    - name: Verify Ansible installation
      run: ansible --version

    - name: Run Ansible Playbook on localhost
      run: |
        ls -la 
        #ansible-playbook site.yml -i localhost, -c local
